<script lang="ts">
	import { formatCurrency } from '$lib/utils/format';
	import { invoiceStatusLabel } from '$lib/utils/format';
	let { data } = $props();
	const stats = $derived([
		{ label: 'Paid revenue', value: formatCurrency(data.metrics.totalRevenue, data.profile.defaultCurrency) },
		{ label: 'Outstanding', value: formatCurrency(data.metrics.outstandingRevenue, data.profile.defaultCurrency) },
		{ label: 'Customers', value: String(data.customerCount) },
		{ label: 'Overdue invoices', value: String(data.metrics.overdueInvoices) }
	]);
</script>
<section class="card no-print flex flex-wrap items-center justify-between gap-4 p-6"><div><p class="text-sm font-medium text-brand-600">Overview</p><h1 class="mt-2 text-3xl font-semibold text-slate-900">Welcome back, keep billing simple.</h1><p class="mt-2 text-sm text-slate-500">Track payments, create invoices, and keep your business profile ready for PDF export.</p></div><div class="flex gap-3"><a class="btn-secondary" href="/app/customers">Add customer</a><a class="btn-primary" href="/app/invoices/new">Create invoice</a></div></section>
<section class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{#each stats as stat}<div class="card p-5"><p class="text-sm text-slate-500">{stat.label}</p><p class="mt-3 text-3xl font-semibold text-slate-900">{stat.value}</p></div>{/each}</section>
<section class="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><div class="card p-6"><div class="mb-5 flex items-center justify-between"><h2 class="text-xl font-semibold text-slate-900">Recent invoices</h2><a href="/app/invoices" class="text-sm font-medium text-brand-600">View all</a></div>{#if data.recentInvoices.length === 0}<div class="rounded-3xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">No invoices yet. Create your first invoice to start tracking revenue.</div>{:else}<div class="space-y-4">{#each data.recentInvoices as invoice}<a href={`/app/invoices/${invoice.id}`} class="flex items-center justify-between rounded-3xl border border-slate-100 px-4 py-4 hover:bg-slate-50"><div><p class="font-medium text-slate-900">{invoice.invoiceNumber}</p><p class="mt-1 text-sm text-slate-500">{invoice.customerName}</p></div><div class="text-right"><span class={`badge badge-${invoice.status}`}>{invoiceStatusLabel(invoice.status)}</span><p class="mt-2 text-sm font-medium text-slate-900">{formatCurrency(invoice.totalAmount, invoice.currency)}</p></div></a>{/each}</div>{/if}</div><div class="card p-6"><h2 class="text-xl font-semibold text-slate-900">Business profile</h2><div class="mt-5 space-y-4 text-sm text-slate-600"><div><p class="text-slate-400">Default currency</p><p class="mt-1 font-medium text-slate-900">{data.profile.defaultCurrency}</p></div><div><p class="text-slate-400">Invoice prefix</p><p class="mt-1 font-medium text-slate-900">{data.profile.invoicePrefix}</p></div><div><p class="text-slate-400">Payment instructions</p><p class="mt-1 whitespace-pre-line">{data.profile.paymentInstructions}</p></div></div></div></section>
