-- Drop tables in reverse order (respecting foreign keys)
DROP TABLE IF EXISTS invoice_items;
DROP TABLE IF EXISTS invoices;
DROP TABLE IF EXISTS service_items;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS business_profiles;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;

-- Recreate tables
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, password_hash TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS business_profiles (user_id TEXT PRIMARY KEY, company_name TEXT NOT NULL, company_email TEXT NOT NULL DEFAULT "", company_phone TEXT NOT NULL DEFAULT "", company_address TEXT NOT NULL DEFAULT "", invoice_prefix TEXT NOT NULL DEFAULT "INV", default_currency TEXT NOT NULL DEFAULT "IDR", payment_instructions TEXT NOT NULL DEFAULT "", logo_url TEXT, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS customers (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, name TEXT NOT NULL, email TEXT NOT NULL DEFAULT "", phone TEXT NOT NULL DEFAULT "", company TEXT NOT NULL DEFAULT "", address TEXT NOT NULL DEFAULT "", notes TEXT NOT NULL DEFAULT "", is_archived INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS service_items (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT "", unit_price REAL NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS invoices (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, customer_id TEXT NOT NULL, invoice_number TEXT NOT NULL UNIQUE, status TEXT NOT NULL DEFAULT "draft", issue_date TEXT NOT NULL, due_date TEXT NOT NULL, currency TEXT NOT NULL DEFAULT "IDR", customer_name TEXT NOT NULL, customer_email TEXT NOT NULL DEFAULT "", customer_address TEXT NOT NULL DEFAULT "", notes TEXT NOT NULL DEFAULT "", payment_instructions TEXT NOT NULL DEFAULT "", subtotal REAL NOT NULL DEFAULT 0, discount_amount REAL NOT NULL DEFAULT 0, tax_percent REAL NOT NULL DEFAULT 0, tax_amount REAL NOT NULL DEFAULT 0, total_amount REAL NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT);

CREATE TABLE IF NOT EXISTS invoice_items (id TEXT PRIMARY KEY, invoice_id TEXT NOT NULL, service_item_id TEXT, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT "", quantity REAL NOT NULL DEFAULT 1, unit_price REAL NOT NULL DEFAULT 0, line_total REAL NOT NULL DEFAULT 0, position INTEGER NOT NULL DEFAULT 0, FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE, FOREIGN KEY (service_item_id) REFERENCES service_items(id) ON DELETE SET NULL);
